version: 2
jobs:
 build:
  # Variable expansion in working_directory not supported at this time
  # You will need to modify the code below to reflect your github account/repo setup
  working_directory: /go/src/github.com/anastasia1201/invoicer-chapter2
  docker:
   - image: circleci/golang:1.10
  steps:
   - checkout
   - setup_remote_docker

   - run: 
      name: Setup environment
      command: |
       gb="/src/github.com/anastasia1201";
       if [ anastasia1201 == 'Securing-DevOps' ]; then
         dr="securingdevops"
       else
         dr=$DOCKER_USER
       fi
       cat >> $BASH_ENV << EOF
       export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"
       export GOPATH_BASE="$(echo ${GOPATH}|cut -d ':' -f 1)${gb}"
       export DOCKER_REPO="$dr"
       EOF
   - run: mkdir -p "${GOPATH_BASE}"
   - run: mkdir -p "${GOPATH_HEAD}/bin"
       
   - run:
      name: Testing application
      command: |
          go test \
          github.com/anastasia1201/invoicer-chapter2

   - deploy:
       command: |
         if [ "${CIRCLE_BRANCH}" == "master" ]; then
           docker login -u anastasia1201 -p Doc_pass$_24o_;
           go install --ldflags '-extldflags "-static"' \
           github.com/anastasia1201/invoicer-chapter2;
           mkdir bin;
           cp "$GOPATH_HEAD/bin/invoicer-chapter2" bin/invoicer;
           docker build -t anastasia1201/invoicer-chapter2 .;
           docker images --no-trunc | awk '/^app/ {print $3}' | \
             sudo tee $CIRCLE_ARTIFACTS/docker-image-shasum256.txt;
           docker push ${DOCKER_REPO}/invoicer-chapter2;
         fi
